package com.dukeacademy.solution.models;

import java.util.Optional;

/**
 * Represents output generated by programs ran by the application.
 */
public class ProgramOutput {
    private String output;
    private Optional<RuntimeError> error;

    /**
     * Instantiates a new Program output.
     */
    public ProgramOutput() {
        this.output = "";
        this.error = Optional.empty();
    }

    /**
     * Gets output.
     *
     * @return the output
     */
    public String getOutput() {
        return this.output;
    }

    /**
     * Gets runtime error.
     *
     * @return the runtime error
     */
    public Optional<RuntimeError> getRuntimeError() {
        return this.error;
    }

    /**
     * Append.
     *
     * @param output the output
     */
    public void append(String output) {
        this.output += output;
    }

    /**
     * Append new line.
     *
     * @param output the output
     */
    public void appendNewLine(String output) {
        this.output += output + "\n";
    }

    /**
     * Gets errored program output.
     *
     * @param errorMessage the error message
     * @return the errored program output
     */
    public static ProgramOutput getErroredProgramOutput(String errorMessage) {
        ProgramOutput output = new ProgramOutput();
        output.error = Optional.of(new RuntimeError(errorMessage));
        return output;
    }
}
