= Alex Koh - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Duke Academy

'''

== Overview

Duke Academy is a Java programming platform equipped with a library of programming questions related to the field of Data Structures and Algorithms, as well as an automated judging system. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 15 kLoC.

== Summary of contributions

* *Major enhancement*: added *bookmark and deletebookmark commands, and also the relevant GUI for these commands - a personal dashboard for the user, which can be found in the Home tab.*
** What it does: bookmark command allows the user to note down a particular question of interest for future reference and/or repeated reference. deletebookmark removes a specific bookmark. The personal dashboard GUI allows the user to conveniently keep track of the bookmarks he has at any point of time.
** Justification: This feature improves user experience significantly. When it comes to programming practise and the study of Data Structures and Algorithms, it is very common for a student to take special note of a few special questions for future reference and/or future reference. There are many reasons why this is the case. For instance, a student preparing might face a question that he find incredibly challenging personally, and hence want to bookmark it for repeated revision. The personal dashboard's GUI allows him to easily keep track the bookmarks he made at a glance, as it this GUI updates according to his entry of a bookmark command or deletebookmark command.
** Highlights: The implementation of bookmark command and deletebookmark command required a deep understanding of the Question class as bookmarks were either added to or removed from questions. Also, the personal dashboard GUI was developed to be able to support other commands implemented by other developers in the team, namely the attempt command and submit command. Hence, it required strong understanding of the relevant parts of the codebase developed by other developers, and more importantly, effective communication with them to deliver an accurate and functional GUI that can support all 4 commands, bookmark, deletebookmark, attempt, submit.

* *Minor enhancement*: added a Program Evaluation Panel that allows the user to view how well his program performed against the pre-defined test cases tied to each question.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=delete]

include::../UserGuide.adoc[tag=dataencryption]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]

include::../DeveloperGuide.adoc[tag=dataencryption]


== PROJECT: PowerPointLabs

'''

_{Optionally, you may include other projects in your portfolio.}_
